
const menuBtn=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav-menu');if(menuBtn){menuBtn.addEventListener('click',()=>nav.classList.toggle('open'))}
document.querySelectorAll('#loginRole,#regRole').forEach(roleSelect=>{const isMobileRole=()=>window.matchMedia('(max-width: 768px)').matches;const expandRole=()=>{if(isMobileRole())roleSelect.size=3};const collapseRole=()=>{roleSelect.size=1};roleSelect.addEventListener('pointerdown',e=>{if(isMobileRole()&&roleSelect.size===1){e.preventDefault();roleSelect.focus();expandRole()}});roleSelect.addEventListener('focus',expandRole);roleSelect.addEventListener('change',()=>{collapseRole();roleSelect.blur()});roleSelect.addEventListener('blur',collapseRole)});
const emailPattern=/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
const roleLabel=role=>role==='admin'?'Marketing Manager':role==='client'?'Client':'';
const showFieldError=(field,message)=>{field.setCustomValidity(message);field.reportValidity();field.focus();field.addEventListener('input',()=>field.setCustomValidity(''),{once:true})};
const activeRole=localStorage.getItem('userRole');
const isLoggedIn=localStorage.getItem('isLoggedIn')==='true'&&(activeRole==='client'||activeRole==='admin');
if(localStorage.getItem('isLoggedIn')==='true'&&!isLoggedIn)localStorage.removeItem('isLoggedIn');
const dashboardPage=document.getElementById('dashContent');
if(dashboardPage&&!isLoggedIn)location.replace('signin.html');
document.querySelectorAll('.nav-menu').forEach(menu=>{const signInLink=menu.querySelector('a[href="signin.html"]');const registerLink=menu.querySelector('a[href="register.html"]');if(isLoggedIn){if(signInLink){signInLink.href=localStorage.getItem('userRole')==='admin'?'admin-dashboard.html':'client-dashboard.html';signInLink.textContent='Dashboard';signInLink.classList.remove('active')}if(registerLink)registerLink.hidden=true}else{if(signInLink)signInLink.hidden=false;if(registerLink)registerLink.hidden=false}});
document.querySelectorAll('[data-alpha]').forEach(i=>i.addEventListener('input',()=>i.value=i.value.replace(/[^a-zA-Z\s]/g,'')));
document.querySelectorAll('[data-number]').forEach(i=>i.addEventListener('input',()=>i.value=i.value.replace(/[^0-9]/g,'')));
const contact=document.getElementById('contactForm');if(contact){contact.addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('contactEmail');const phone=document.getElementById('contactPhone');const emailOk=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim());const phoneOk=/^[0-9]{10}$/.test(phone.value.trim());if(!emailOk){alert('Please enter a valid email address (name@example.com).');email.focus();return}if(!phoneOk){alert('Please enter a valid 10 digit phone number.');phone.focus();return}location.href='404.html'})}
const signin=document.getElementById('signinForm');if(signin){signin.addEventListener('submit',e=>{e.preventDefault();const emailEl=document.getElementById('loginEmail');const roleEl=document.getElementById('loginRole');const email=emailEl.value.trim();const p=document.getElementById('loginPassword').value;const r=roleEl.value;emailEl.setCustomValidity('');roleEl.setCustomValidity('');if(!emailPattern.test(email)){showFieldError(emailEl,'Please enter a valid email address, for example user@domain.com.');return}if(p.length<6){alert('Password minimum 6 characters.');return}if(!r){showFieldError(roleEl,'Please select your account role.');return}const registeredEmail=localStorage.getItem('registeredEmail');const registeredRole=localStorage.getItem('registeredRole');if(registeredEmail&&registeredEmail.toLowerCase()!==email.toLowerCase()){showFieldError(emailEl,'No registered account found for this email. Please create an account first.');return}if(registeredRole&&registeredRole!==r){showFieldError(roleEl,`This account was registered as ${roleLabel(registeredRole)}. Please select the same role.`);return}const name=registeredEmail?localStorage.getItem('registeredName')||'User':localStorage.getItem('userName')||'User';localStorage.setItem('isLoggedIn','true');localStorage.setItem('userEmail',email);localStorage.setItem('userRole',r);localStorage.setItem('userName',name);location.href=r==='client'?'client-dashboard.html':'admin-dashboard.html'})}
const reg=document.getElementById('registerForm');if(reg){reg.addEventListener('submit',e=>{e.preventDefault();const emailEl=document.getElementById('regEmail');const phoneEl=document.getElementById('regPhone');const roleEl=document.getElementById('regRole');const email=emailEl.value.trim();const phone=phoneEl.value.trim();const role=roleEl.value;const p=document.getElementById('regPass').value,c=document.getElementById('regConfirm').value;emailEl.setCustomValidity('');phoneEl.setCustomValidity('');roleEl.setCustomValidity('');if(!emailPattern.test(email)){showFieldError(emailEl,'Please enter a valid email address, for example user@domain.com.');return}if(!/^[0-9]{10}$/.test(phone)){showFieldError(phoneEl,'Please enter exactly 10 numeric digits.');return}if(!role){showFieldError(roleEl,'Please select an account role.');return}if(p.length<6){alert('Password minimum 6 characters');return}if(p!==c){alert('Password and Confirm Password must match');return}const name=document.getElementById('regName').value.trim()||'User';localStorage.setItem('registeredName',name);localStorage.setItem('registeredEmail',email);localStorage.setItem('registeredPhone',phone);localStorage.setItem('registeredRole',role);document.getElementById('regMsg').textContent=`Account created successfully as ${roleLabel(role)}. Please sign in now.`;setTimeout(()=>location.href='signin.html',1200)})}
const welcome=document.getElementById('dashboardWelcome');if(welcome){const name=localStorage.getItem('userName')||'User';const email=localStorage.getItem('userEmail')||'Not available';const role=localStorage.getItem('userRole')||'Not selected';document.getElementById('welcomeTitle').textContent=`Welcome, ${name}`;document.getElementById('welcomeName').textContent=name;document.getElementById('welcomeEmail').textContent=email;document.getElementById('welcomeRole').textContent=role==='admin'?'Marketing Manager':role==='client'?'Client':role}
const clientPanels={
Overview:['Listener Overview','Your listening performance, subscribed podcasts, saved episodes, recent plays, and weekly activity are summarized here.','<div class="dash-grid"><div class="dash-card"><span>Saved Podcasts</span><strong>36</strong></div><div class="dash-card"><span>Hours Listened</span><strong>128</strong></div><div class="dash-card"><span>Subscriptions</span><strong>18</strong></div><div class="dash-card"><span>New Alerts</span><strong>12</strong></div></div>'],
Podcasts:['Subscribed Podcasts','Manage your favorite shows, followed creators, and recommended podcast collections.','<div class="dash-list"><div>Founder Frequency • New episode available</div><div>Market Mic • Weekly business update</div><div>Wellness Waves • Saved for later</div></div>'],
Episodes:['Saved & Recent Episodes','View recently played episodes, continue listening, and manage your saved queue.','<table class="table"><tr><th>Episode</th><th>Duration</th><th>Status</th></tr><tr><td>Audio Ads That Convert</td><td>28 min</td><td><span class="badge">Saved</span></td></tr><tr><td>Future of Streaming</td><td>45 min</td><td><span class="badge">Playing</span></td></tr></table>'],
Analytics:['Listening Analytics','Analyze your listening habits, completion rate, preferred categories, and weekly activity.','<div class="line-chart"><span></span><span></span><span></span><span></span><span></span></div>'],
Listeners:['Community Insights','See listener groups, creator communities, and audience trends around your subscribed shows.','<div class="dash-grid"><div class="dash-card"><span>Community Rank</span><strong>Top 8%</strong></div><div class="dash-card"><span>Reviews Added</span><strong>24</strong></div></div>'],
Reports:['Personal Reports','Download monthly listening reports and saved content summaries.','<div class="dash-list"><div>May Listening Report</div><div>Top Categories Report</div><div>Saved Episodes Export</div></div>'],
Messages:['Messages','Creator updates, platform notifications, and support replies appear here.','<div class="dash-list"><div>STACKLY Support: Your report is ready.</div><div>Founder Frequency: New bonus episode released.</div></div>'],
Settings:['Account Settings','Manage profile preferences, notifications, privacy, and playback settings.','<div class="dash-list"><div>Email Notifications: Enabled</div><div>Autoplay: Enabled</div><div>Theme: Navy Blue</div></div>']
};
const adminPanels={
Overview:['Manager Overview','Monitor podcast performance, campaign results, revenue, listener growth, and team updates.','<div class="dash-grid"><div class="dash-card"><span>Active Shows</span><strong>84</strong></div><div class="dash-card"><span>Uploads</span><strong>312</strong></div><div class="dash-card"><span>Campaigns</span><strong>27</strong></div><div class="dash-card"><span>Revenue</span><strong>₹18.4L</strong></div></div>'],
Podcasts:['Podcast Management','Create, update, publish, and organize podcast collections for different categories.','<table class="table"><tr><th>Show</th><th>Category</th><th>Status</th></tr><tr><td>Founder Frequency</td><td>Business</td><td><span class="badge">Live</span></td></tr><tr><td>Health Audio Lab</td><td>Health</td><td><span class="badge">Scheduled</span></td></tr></table>'],
Episodes:['Episode Uploads','Manage episode titles, duration, upload status, thumbnails, and publishing schedule.','<div class="dash-list"><div>Upload: Future of Streaming • Ready</div><div>Edit: Audio Ads That Convert • Draft</div><div>Schedule: Wellness Waves • Tomorrow</div></div>'],
Analytics:['Platform Analytics','Track listening trends, completion rate, retention, category performance, and listener growth.','<div class="line-chart"><span></span><span></span><span></span><span></span><span></span></div>'],
Listeners:['Listener Growth','Review audience segments, repeat listeners, new subscribers, and engagement quality.','<div class="dash-grid"><div class="dash-card"><span>New Listeners</span><strong>18.2K</strong></div><div class="dash-card"><span>Retention</span><strong>72%</strong></div></div>'],
Revenue:['Revenue Metrics','Analyze subscription revenue, sponsorship income, audio ad earnings, and monthly growth.','<div class="dash-grid"><div class="dash-card"><span>MRR</span><strong>₹7.8L</strong></div><div class="dash-card"><span>Ad Revenue</span><strong>₹4.2L</strong></div><div class="dash-card"><span>Sponsors</span><strong>19</strong></div></div>'],
Reports:['Reports','Generate performance reports for episodes, campaigns, revenue, and listener analytics.','<div class="dash-list"><div>Campaign ROI Report</div><div>Episode Performance Report</div><div>Revenue Forecast Report</div></div>'],
Messages:['Messages','View creator messages, client requests, support tickets, and internal notes.','<div class="dash-list"><div>Client: Need campaign report</div><div>Creator: Episode upload completed</div><div>Support: Map issue fixed</div></div>'],
Settings:['Platform Settings','Manage dashboard preferences, team roles, notification rules, and publishing controls.','<div class="dash-list"><div>Team Access: 6 managers</div><div>Auto Reports: Enabled</div><div>Brand Theme: Navy Blue</div></div>']
};
document.querySelectorAll('.sidebar button').forEach(btn=>btn.addEventListener('click',()=>{const name=btn.textContent.trim();if(btn.dataset.panel==='sign-out'){localStorage.removeItem('isLoggedIn');localStorage.removeItem('userEmail');localStorage.removeItem('userRole');localStorage.removeItem('userName');localStorage.removeItem('stacklyLogin');location.href='index.html';return}const el=document.getElementById('dashContent');const mode=el?.dataset.dashboard;const data=(mode==='admin'?adminPanels:clientPanels)[name]||clientPanels[name]||adminPanels[name];el.innerHTML=`<div class="panel"><h2>${data[0]}</h2><p>${data[1]}</p>${data[2]}</div>`;}));
